language: go
cache:
  directories:
    - $HOME/.glide/cache
go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
install: make install_ci
env:
 # Set higher timeouts for Travis
 - TEST_TIMEOUT_SCALE=20
script:
 - make test_ci
 - make cover_ci
 - make lint

